sudo: required
services:
  - docker

before_install:
  - docker build -t victorhvargas/react-test -f ./client/Dockerfile.dev .

script:
  - docker run victorhvargas/react-test npm test -- --coverage

after_success:
  - docker build -t victorhvargas/multi-client ./client
  - docker build -t victorhvargas/multi-nginx ./nginx
  - docker build -t victorhvargas/multi-server ./server
  - docker build -t victorhvargas/multi-worker ./worker
